# docker-compose config for workflow-automation-rails

web:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - .:/usr/src/app
  links:
    - postgres
  environment:
    - TWILIO_ACCOUNT_SID
    - TWILIO_AUTH_TOKEN
    - TWILIO_NUMBER

postgres:
  image: postgres:9.4
